---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "awx-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "awx-operator.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "awx-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
