---
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "code-server.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ $fullName }}
    app.kubernetes.io/component: "ingress"
    app.kubernetes.io/part-of: {{ $fullName }}
spec:
  entryPoints:
  - websecure
  tls:
    secretName: {{ $fullName }}-traefik-tls
  routes:
  - kind: Rule
    match: "Host(`code.arroyo.turnbros.app`)"
    middlewares: []
    services:
    - kind: Service
      name: {{ $fullName }}
      namespace: code-server
      port: {{ $svcPort }}
      scheme: http

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ $fullName }}
    app.kubernetes.io/component: "certificate"
    app.kubernetes.io/part-of: {{ $fullName }}
spec:
  commonName: code.arroyo.turnbros.app
  secretName: {{ $fullName }}-traefik-tls
  dnsNames:
  - code.arroyo.turnbros.app
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
{{- end }}
