---
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "code-server.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
  - websecure
  - web
  tls:
    secretName: {{ $fullName }}-traefik-tls
  routes:
  - kind: Rule
    match: "Host('code.arroyo.turnbros.app')"
    middlewares: []
    services:
    - kind: Service
      name: {{ $fullName }}
      port: {{ $svcPort }}
      scheme: http

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  commonName: code.arroyo.turnbros.app
  secretName: {{ $fullName }}-traefik-tls
  dnsNames:
  - code.arroyo.turnbros.app
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
{{- end }}
