---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "code-server.fullname" . }}
  annotations:
    "helm.sh/hook": "pre-install"
  labels:
    app.kubernetes.io/name: {{ include "code-server.name" . }}
    helm.sh/chart: {{ include "code-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  config.yaml: |-
    auth: {{ .Values.auth.enabledMethod }}
    {{ if eq "password" .Values.auth.enabledMethod }}
    {{ if .Values.auth.password }}
    password: {{ .Values.auth.password }}
    {{ else }}
    password: {{ randAlphaNum 24 }}
    {{ end }}
    {{ end }}
    {{ if eq "openid" .Values.auth.enabledMethod }}
    openid-issuer-base-url: {{ .Values.auth.openId.issuerBaseUrl }}
    openid-base-url: {{ .Values.auth.openId.baseUrl }}
    openid-client-id: {{ .Values.auth.openId.clientId }}
    openid-secret: {{ randAlphaNum 24 }}
    {{ if .Values.auth.openId.groupClaim }}
    openid-group-claim: {{ .Values.auth.openId.groupClaim }}
    openid-user-group: {{ .Values.auth.openId.userGroup }}
    {{ end }}
    {{ end }}
