{{- range $external_secret := .Values.external_secrets }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ $external_secret.name }}
  namespace: {{ .Release.Namespace }}
spec:
  backendType: {{ $external_secret.backend_type }} # Gotta be vault tho!
  vaultMountPoint: {{ $external_secret.vault_mount_point }}
  vaultRole: {{ $external_secret.vault_role }}
  data:
  {{ $external_secret.secrets }}
{{- end }}